modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="itsalonplayz_god_sword"
version="1.0.0"
displayName="ItsAlonPlayz God Sword"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="alonp, MCreator"

[[dependencies.itsalonplayz_god_sword]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




